### ISSUE TITLE
Move Quality Checklist to this repo and provide links to evidence

### ISSUE THREAD

**Issue by katherinemendel** [404NameNotFound404/SolitaireSimulation#11]

**Comment by mia-li-001** [comment]
Make a Wiki page for it, does it work?

**Comment by katherinemendel** [comment]
For some reason, it won’t let me check off any boxes if it’s in a wiki - and I can’t add comments so we can put evidence… Maybe that’s just an issue with my computer?

-Katie

**Comment by katherinemendel** [comment]
Thanks, @mia-li-z!
